name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: egor-tensin/setup-clang@v1

    - name: Ship
      shell: pwsh
      run: ./.github/workflows/shipper.ps1

#    - name: Compress binaries
#      uses: svenstaro/upx-action@v2
#      with:
#        args: -9
#        files: |
#          smoothie-rs-artifact/bin/smoothie*.exe
#          smoothie-rs-artifact/bin/vapoursynth64/plugins/*.dll

    - uses: actions/upload-artifact@v3
      with:
        name: smoothie-rs-bin-windows
        path: ./smoothie-rs/

    - name: Generate release tag
      id: tag
      run: echo "::set-output name=release_tag::Nightly_$(date +"%Y.%m.%d_%H-%M")"

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        fail_on_unmatched_files: true
        files: |
          ./smoothie-rs-nightly.zip
